# payments/models.py
from decimal import Decimal
from django.db import models
from django.conf import settings


class PaymentMethod(models.TextChoices):
    CASH = "CASH", "Cash"
    BANK = "BANK", "Bank Transfer"
    MPESA = "MPESA", "Mobile Money"
    CHEQUE = "CHEQUE", "Cheque"


class Payment(models.Model):
    """
    A payment from a client towards a premium installment.

    Business context:
    - Ripple Capital collects this on behalf of the insurer.
    - The full amount is premium (liability to insurer).
    - Commission is calculated separately via the commissions app.

    Payment → PremiumInstallment (many-to-one)
    """

    installment = models.ForeignKey(
        "policies.PremiumInstallment",
        on_delete=models.PROTECT,
        related_name="payments",
    )
    amount = models.DecimalField(
        max_digits=14,
        decimal_places=2,
        help_text="Amount received from client as premium.",
    )
    method = models.CharField(
        max_length=20,
        choices=PaymentMethod.choices,
        default=PaymentMethod.CASH,
    )
    reference_number = models.CharField(
        max_length=100,
        blank=True,
        help_text="Bank reference, M-Pesa transaction ID, cheque number, etc.",
    )
    received_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="payments_received",
        help_text="Ripple Capital staff who recorded this payment.",
    )
    payment_date = models.DateTimeField(auto_now_add=True)
    receipt_number = models.CharField(
        max_length=50,
        unique=True,
        help_text="Internal receipt number generated by the ERP.",
    )

    class Meta:
        ordering = ["-payment_date"]
        verbose_name = "Payment"
        verbose_name_plural = "Payments"
        indexes = [
            models.Index(fields=["receipt_number"]),
            models.Index(fields=["payment_date"]),
        ]

    def __str__(self):
        return f"Receipt {self.receipt_number} - {self.amount} (Policy {self.installment.policy.policy_number})"

    @property
    def policy(self):
        return self.installment.policy

    @property
    def client(self):
        return self.installment.policy.client

    @property
    def insurer(self):
        return self.installment.policy.insurance_company
